#!/bin/sh
set -eu

lb config noauto \
  --mode debian \
  --distribution trixie \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --system live \
  --debian-installer live \
  --archive-areas "main contrib non-free-firmware" \
  --security true \
  --updates true \
  --iso-application "Chepian Server" \
  --iso-publisher "Chepian Project" \
  --iso-volume "CHEPIAN_SERVER" \
  --bootappend-live "boot=live components hostname=chepian username=chep" \
  "$@"
